name:                myocardio
version:             2.0.0
github:              "pmiddend/myocardio"
license:             BSD3
author:              "Philipp Middendorf"
maintainer:          "pmidden@mailbox.org"
copyright:           "2022 Philipp Middendorf"

extra-source-files:
- README.org

description:         Please see the README on GitHub at <https://github.com/pmiddend/myocardio#readme>

ghc-options:
- -Weverything
- -Wno-missing-safe-haskell-mode
- -Wno-unsafe
- -Wno-missing-deriving-strategies
- -Wno-all-missed-specialisations
- -Wno-monomorphism-restriction
- -Wno-safe
- -Wno-missing-local-signatures
# https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/import_qualified_post.html
# Only makes sense with the language extension enabled
- -Wno-prepositive-qualified-module
- -threaded
- -rtsopts
- -with-rtsopts=-N


library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - microlens-platform
  - microlens
  - time
  - text
  - aeson
  - containers

executables:
  myocardio-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - base >= 4.7 && < 5
    - myocardio
    - brick
    - bytestring
    - microlens
    - haskeline
    - microlens-platform
    - aeson-pretty
    - xdg-basedir
    - text
    - time
    - aeson
    - http-client-tls
    - http-client
    - text-zipper
    - vty
    - containers
    - directory

tests:
  myocardio-test:
    main:                Spec.hs
    source-dirs:         test-suite
    dependencies:
    - myocardio
    - hspec
    - base >= 4.7 && < 5
    - QuickCheck
    - quickcheck-instances
    - time
