name: "Build statically with Nix"
on: [push]
jobs:
  build-static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build
    - name: Archive static build
      uses: actions/upload-artifact@v3
      with:
        name: Static executable
        path: result/bin/myocardio-exe
