name: "Build statically with Nix"
on: [push]
jobs:
  build-static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v19
    - run: nix build .#myocardio-static
    - run nix flake check
    - name: Archive static build
      uses: actions/upload-artifact@v3
      with:
        name: Static executable
        path: result/bin/myocardio-exe
